package de.tadris.fitness.converter;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class ScientificNameConverter {

    public String convertToCommonName(String scientificName) {

        Map<String, String> birdNames = new HashMap<>();

        birdNames.put("Haemorhous cassinii", "Cassin's Finch");
        birdNames.put("Aramus guarauna", "Limpkin");
        birdNames.put("Rupornis magnirostris",  "Roadside Hawk");
        birdNames.put("Cyanocitta cristata",  "Blue Jay");
        birdNames.put("Cyanocitta stelleri",  "Steller's Jay");
        birdNames.put("Balearica regulorum",  "Grey Crowned Crane");
        birdNames.put("Pyrocephalus rubinus",  "Vermilion Flycatcher");
        birdNames.put("Recurvirostra americana",  "Red-necked avocet");
        birdNames.put("Ardeotis kori",  "Kori Bustard");
        birdNames.put("Pica nuttalli",  "");
        birdNames.put("Perisoreus canadensis",  "");
        birdNames.put("Antigone canadensis",  "");
        birdNames.put("Parkesia noveboracensis",  "");
        birdNames.put("Ardea herodias occidentalis",  "");
        birdNames.put("Porzana carolina",  "");
        birdNames.put("Anas platyrhynchos diazi",  "");
        birdNames.put("Motacilla cinerea",  "");
        birdNames.put("Empidonax difficilis",  "");
        birdNames.put("Empidonax minimus",  "");
        birdNames.put("Empidonax fulvifrons",  "");
        birdNames.put("Empidonax traillii",  "");
        birdNames.put("Empidonax hammondii",  "");
        birdNames.put("Empidonax occidentalis",  "");
        birdNames.put("Rallus limicola",  "");
        birdNames.put("Grus grus",  "");
        birdNames.put("Quiscalus major",  "");
        birdNames.put("Branta leucopsis",  "");
        birdNames.put("Cyanocorax yucatanicus",  "");
        birdNames.put("Cyanocorax yncas",  "");
        birdNames.put("Oceanites oceanicus",  "Wilson's storm petrel");
        birdNames.put("Quiscalus niger",  "");
        birdNames.put("Psilorhinus morio",  "");
        birdNames.put("Megarynchus pitangua",  "");
        birdNames.put("Gallinula tenebrosa",  "Moorhen");
        birdNames.put("Gallus gallus domesticus",  "Domestic Chicken");
        birdNames.put("Numida meleagris",  "Helmeted Guineafowl");
        birdNames.put("Junco hyemalis caniceps",  "");
        birdNames.put("Tyrannus vociferans",  "");
        birdNames.put("Tyrannus tyrannus",  "");
        birdNames.put("Tyrannus forficatus",  "");
        birdNames.put("Tyrannus crassirostris",  "");
        birdNames.put("Tyrannus verticalis",  "");
        birdNames.put("Tyrannus savana",  "");
        birdNames.put("Gallirallus australis",  "Weka");
        birdNames.put("Calocitta formosa",  "");
        birdNames.put("Calocitta colliei",  "");
        birdNames.put("Fulica americana",  "");
        birdNames.put("Pachyramphus aglaiae",  "");
        birdNames.put("Buteo lagopus",  "");
        birdNames.put("Cygnus atratus",  "Black Swan");
        birdNames.put("Philesturnus rufusater",  "Tīeke");
        birdNames.put("Larus marinus",  "");
        birdNames.put("Pitangus sulphuratus",  "");
        birdNames.put("Anas rubripes",  "");
        birdNames.put("Anthus novaeseelandiae novaeseelandiae",  "Pipit");
        birdNames.put("Sayornis phoebe",  "");
        birdNames.put("Sayornis nigricans",  "");
        birdNames.put("Tityra semifasciata",  "");
        birdNames.put("Dryocopus lineatus",  "");
        birdNames.put("Porphyrio melanotus",  "Pūkeko");
        birdNames.put("Anas bahamensis",  "");
        birdNames.put("Egretta novaehollandiae",  "White-faced heron");
        birdNames.put("Anas crecca carolinensis",  "");
        birdNames.put("Alectoris chukar",  "Chukar");
        birdNames.put("Tachybaptus dominicus",  "Grebe");
        birdNames.put("Artemisiospiza belli",  "");
        birdNames.put("Gallus gallus",  "Red Junglefowl");
        birdNames.put("Cardinalis sinuatus",  "");
        birdNames.put("Cardinalis cardinalis",  "");
        birdNames.put("Melospiza lincolnii",  "");
        birdNames.put("Podilymbus podiceps",  "");
        birdNames.put("Melospiza georgiana",  "");
        birdNames.put("Meleagris gallopavo",  "Wild Turkey");
        birdNames.put("Meleagris ocellata",  "");
        birdNames.put("Lagopus lagopus",  "");
        birdNames.put("Spizella atrogularis",  "");
        birdNames.put("Pyrrhocorax graculus",  "");
        birdNames.put("Spizella breweri",  "");
        birdNames.put("Sialia currucoides",  "");
        birdNames.put("Spizella pusilla",  "");
        birdNames.put("Anas superciliosa",  "Grey Duck");
        birdNames.put("Passerella iliaca",  "");
        birdNames.put("Phoenicopterus ruber",  "");
        birdNames.put("Sylvia atricapilla",  "");
        birdNames.put("Vireo bellii",  "");
        birdNames.put("Vireo plumbeus",  "");
        birdNames.put("Vireo philadelphicus",  "");
        birdNames.put("Vireo flavifrons",  "");
        birdNames.put("Vireo olivaceus",  "");
        birdNames.put("Zonotrichia querula",  "");
        birdNames.put("Vireo huttoni",  "");
        birdNames.put("Zonotrichia albicollis",  "");
        birdNames.put("Zonotrichia atricapilla",  "");
        birdNames.put("Emberiza citrinella",  " Yellowhammer");
        birdNames.put("Bucephala islandica",  "");
        birdNames.put("Emberiza schoeniclus",  "");
        birdNames.put("Vireo gilvus",  "");
        birdNames.put("Serinus serinus",  "");
        birdNames.put("Serinus mozambicus",  "");
        birdNames.put("Lophura leucomelanos",  "");
        birdNames.put("Euphonia elegantissima",  "");
        birdNames.put("Euphonia hirundinacea",  "");
        birdNames.put("Euphonia affinis",  "");
        birdNames.put("Agelaius tricolor",  "");
        birdNames.put("Momotus lessonii",  "");
        birdNames.put("Zosterops japonicus",  "");
        birdNames.put("Phalacrocorax pelagicus",  "");
        birdNames.put("Icterus cucullatus",  "");
        birdNames.put("Icterus graduacauda",  "");
        birdNames.put("Motacilla aguimp",  "");
        birdNames.put("Anas superciliosa × platyrhynchos",  "Grey Duck");
        birdNames.put("Icterus pustulatus",  "");
        birdNames.put("Icterus gularis",  "");
        birdNames.put("Carduelis cannabina",  "");
        birdNames.put("Catharus minimus",  "");
        birdNames.put("Amaurornis phoenicurus",  "");
        birdNames.put("Pavo cristatus",  "Peafowl");
        birdNames.put("Rallus crepitans",  "");
        birdNames.put("Nestor meridionalis septentrionalis",  "Kākā");
        birdNames.put("Pipilo chlorurus",  "");
        birdNames.put("Pipilo maculatus",  "");
        birdNames.put("Pipilo erythrophthalmus",  "");
        birdNames.put("Cairina moschata domestica",  "Domestic Muscovy Duck");
        birdNames.put("Phalacrocorax varius",  "Pied shag");
        birdNames.put("Picoides dorsalis",  "");
        birdNames.put("Picoides nuttallii",  "");
        birdNames.put("Picoides scalaris",  "");
        birdNames.put("Callipepla gambelii",  "");
        birdNames.put("Pyrrhula pyrrhula",  "");
        birdNames.put("Phalacrocorax brasilianus",  "");
        birdNames.put("Picoides pubescens",  "");
        birdNames.put("Colinus virginianus",  "");
        birdNames.put("Sporophila torqueola",  "");
        birdNames.put("Picoides villosus",  "");
        birdNames.put("Calidris pusilla",  "");
        birdNames.put("Picoides arcticus",  "");
        birdNames.put("Aythya marila",  "Scaup");
        birdNames.put("Phaethon aethereus",  "Tropicbird");
        birdNames.put("Sturnella magna",  "");
        birdNames.put("Melopsittacus undulatus",  "Budgerigar");
        birdNames.put("Aythya affinis",  "");
        birdNames.put("Aythya novaeseelandiae",  "Scaup");
        birdNames.put("Cyrtonyx montezumae",  "");
        birdNames.put("Pelecanus occidentalis",  "");
        birdNames.put("Cinclus cinclus",  "");
        birdNames.put("Chen rossii",  "");
        birdNames.put("Callipepla californica",  "California Quail");
        birdNames.put("Quiscalus quiscula",  "");
        birdNames.put("Quiscalus mexicanus",  "");
        birdNames.put("Callipepla squamata",  "");
        birdNames.put("Dryocopus pileatus",  "");
        birdNames.put("Passerina caerulea",  "");
        birdNames.put("Amazilia beryllina",  "");
        birdNames.put("Geothlypis trichas",  "");
        birdNames.put("Trogon melanocephalus",  "");
        birdNames.put("Sylvia communis",  "");
        birdNames.put("Pinicola enucleator",  "");
        birdNames.put("Coccothraustes vespertinus",  "");
        birdNames.put("Coccothraustes coccothraustes",  "");
        birdNames.put("Vermivora chrysoptera",  "");
        birdNames.put("Opisthocomus hoazin",  "");
        birdNames.put("Setophaga coronata coronata",  "");
        birdNames.put("Diglossa baritula",  "");
        birdNames.put("Saltator coerulescens",  "");
        birdNames.put("Saltator atriceps",  "");
        birdNames.put("Sicalis flaveola",  "");
        birdNames.put("Aix galericulata",  "Mandarin Duck");
        birdNames.put("Junco hyemalis hyemalis",  "");
        birdNames.put("Eupsittula canicularis",  "");
        birdNames.put("Microcarbo melanoleucos",  "Little Shag");
        birdNames.put("Piranga rubra",  "");
        birdNames.put("Piranga olivacea",  "");
        birdNames.put("Piranga flava",  "");
        birdNames.put("Amphispiza bilineata",  "");
        birdNames.put("Larus dominicanus",  "Black-backed Gull");
        birdNames.put("Piaya cayana",  "");
        birdNames.put("Aimophila ruficeps",  "");
        birdNames.put("Melanerpes lewis",  "");
        birdNames.put("Melanerpes uropygialis",  "");
        birdNames.put("Passerculus sandwichensis",  "");
        birdNames.put("Melanerpes pucherani",  "");
        birdNames.put("Salpinctes obsoletus",  "");
        birdNames.put("Melanerpes carolinus",  "");
        birdNames.put("Melanerpes chrysogenys",  "");
        birdNames.put("Melanerpes formicivorus",  "");
        birdNames.put("Colaptes auratus",  "");
        birdNames.put("Basileuterus rufifrons",  "");
        birdNames.put("Larus michahellis",  "");
        birdNames.put("Ramphocelus passerinii",  "");
        birdNames.put("Athene cunicularia",  "");
        birdNames.put("Branta hutchinsii",  "");
        birdNames.put("Fringilla montifringilla",  "");
        birdNames.put("Fringilla coelebs", "Chaffinch");
        birdNames.put("Junco hyemalis",  "");
        birdNames.put("Cuculus canorus",  "Cuckoo");
        birdNames.put("Junco phaeonotus",  "");
        birdNames.put("Ammodramus nelsoni",  "");
        birdNames.put("Ammodramus savannarum",  "");
        birdNames.put("Ammodramus maritimus",  "");
        birdNames.put("Coccyzus erythropthalmus",  "");
        birdNames.put("Coccyzus minor",  "");
        birdNames.put("Coccyzus americanus",  "");
        birdNames.put("Nucifraga columbiana",  "");
        birdNames.put("Crotophaga sulcirostris",  "");
        birdNames.put("Pooecetes gramineus",  "");
        birdNames.put("Arremonops rufivirgatus",  "");
        birdNames.put("Geococcyx californianus",  "");
        birdNames.put("Geococcyx velox",  "");
        birdNames.put("Coereba flaveola",  "");
        birdNames.put("Passerina ciris",  "");
        birdNames.put("Alectura lathami",  "");
        birdNames.put("Passerina leclancherii",  "");
        birdNames.put("Passerina amoena",  "");
        birdNames.put("Icteria virens",  "");
        birdNames.put("Crax rubra",  "");
        birdNames.put("Penelope purpurascens",  "");
        birdNames.put("Copsychus malabaricus",  "");
        birdNames.put("Paroaria capitata",  "");
        birdNames.put("Cyanerpes cyaneus",  "");
        birdNames.put("Microcarbo melanoleucos brevirostris",  "Little Shag");
        birdNames.put("Sphyrapicus thyroideus",  "");
        birdNames.put("Pheucticus ludovicianus",  "");
        birdNames.put("Sphyrapicus ruber",  "");
        birdNames.put("Pheucticus melanocephalus",  "");
        birdNames.put("Sphyrapicus nuchalis",  "");
        birdNames.put("Ortalis poliocephala",  "");
        birdNames.put("Ortalis vetula",  "");
        birdNames.put("Corvus albus",  "");
        birdNames.put("Mniotilta varia",  "");
        birdNames.put("Volatinia jacarina",  "");
        birdNames.put("Thraupis palmarum",  "");
        birdNames.put("Momotus mexicanus",  "");
        birdNames.put("Euphagus cyanocephalus",  "");
        birdNames.put("Cacatua galerita",  "Sulphur-crested Cockatoo");
        birdNames.put("Junco hyemalis oreganus",  "");
        birdNames.put("Pluvialis fulva",  "Golden Plover");
        birdNames.put("Molothrus aeneus",  "");
        birdNames.put("Molothrus ater",  "");
        birdNames.put("Merops pusillus",  "");
        birdNames.put("Merops apiaster",  "");
        birdNames.put("Pteroglossus torquatus",  "");
        birdNames.put("Loxia curvirostra",  "");
        birdNames.put("Merops orientalis",  "");
        birdNames.put("Loxia leucoptera",  "");
        birdNames.put("Coracias garrulus",  "");
        birdNames.put("Coracias caudatus",  "");
        birdNames.put("Coracias benghalensis",  "");
        birdNames.put("Xanthocephalus xanthocephalus",  "");
        birdNames.put("Chondestes grammacus",  "");
        birdNames.put("Dolichonyx oryzivorus",  "");
        birdNames.put("Pandion haliaetus",  "");
        birdNames.put("Phainopepla nitens",  "");
        birdNames.put("Tyrannus couchii",  "");
        birdNames.put("Phylloscopus collybita",  "");
        birdNames.put("Circus cyaneus hudsonius",  "");
        birdNames.put("Grallina cyanoleuca",  "");
        birdNames.put("Plectrophenax nivalis",  "");
        birdNames.put("Calamospiza melanocorys",  "");
        birdNames.put("Regulus calendula",  "");
        birdNames.put("Regulus ignicapilla",  "");
        birdNames.put("Regulus regulus",  "");
        birdNames.put("Regulus satrapa",  "");
        birdNames.put("Tyrannus melancholicus",  "");
        birdNames.put("Pelecanus conspicillatus",  "Australian pelican");
        birdNames.put("Aulacorhynchus prasinus",  "");
        birdNames.put("Todiramphus sanctus",  "Kingfisher");
        birdNames.put("Icterus bullockii",  "");
        birdNames.put("Spiza americana",  "");
        birdNames.put("Tyrannus dominicensis",  "");
        birdNames.put("Chlidonias niger",  "Black Tern");
        birdNames.put("Oriturus superciliosus",  "");
        birdNames.put("Psarocolius montezuma",  "");
        birdNames.put("Turdus pilaris",  "");
        birdNames.put("Notiomystis cincta",  "Hihi");
        birdNames.put("Sagittarius serpentarius",  "");
        birdNames.put("Psittacula krameri",  "Parakeet");
        birdNames.put("Platycercus eximius",  "Rosella");
        birdNames.put("Protonotaria citrea",  "");
        birdNames.put("Megaceryle torquata",  "");
        birdNames.put("Nestor meridionalis",  "Kākā");
        birdNames.put("Amazona viridigenalis",  "");
        birdNames.put("Amazona albifrons",  "");
        birdNames.put("Amazona oratrix",  "");
        birdNames.put("Saxicola rubetra",  "");
        birdNames.put("Ara militaris",  "");
        birdNames.put("Spizelloides arborea",  "");
        birdNames.put("Ceryle rudis",  "");
        birdNames.put("Chloroceryle aenea",  "");
        birdNames.put("Chloroceryle amazona",  "");
        birdNames.put("Myiozetetes similis",  "");
        birdNames.put("Toxostoma curvirostre",  "");
        birdNames.put("Megaceryle alcyon",  "");
        birdNames.put("Eremophila alpestris",  "");
        birdNames.put("Alisterus scapularis",  "Australian King-Parrot");
        birdNames.put("Cinnyris jugularis",  "");
        birdNames.put("Xiphorhynchus flavigaster",  "");
        birdNames.put("Jacana jacana",  "");
        birdNames.put("Phalaropus fulicarius",  "Red Phalarope");
        birdNames.put("Streptopelia turtur",  "Dove");
        birdNames.put("Pica hudsonia",  "");
        birdNames.put("Corvus cornix",  "");
        birdNames.put("Myiopsitta monachus",  "");
        birdNames.put("Streptopelia decaocto",  "Dove");
        birdNames.put("Piranga ludoviciana",  "");
        birdNames.put("Ixobrychus exilis",  "");
        birdNames.put("Auriparus flaviceps",  "");
        birdNames.put("Geothlypis tolmiei",  "");
        birdNames.put("Columba livia",  "Pigeon");
        birdNames.put("Setophaga citrina",  "");
        birdNames.put("Setophaga cerulea",  "");
        birdNames.put("Columba palumbus",  "");
        birdNames.put("Piranga bidentata",  "");
        birdNames.put("Patagioenas leucocephala",  "");
        birdNames.put("Patagioenas fasciata",  "");
        birdNames.put("Patagioenas flavirostris",  "");
        birdNames.put("Setophaga discolor",  "");
        birdNames.put("Chordeiles minor",  "");
        birdNames.put("Chordeiles acutipennis",  "");
        birdNames.put("Platalea leucorodia",  "");
        birdNames.put("Phalaenoptilus nuttallii",  "");
        birdNames.put("Haemorhous mexicanus",  "");
        birdNames.put("Haemorhous purpureus",  "");
        birdNames.put("Nyctidromus albicollis",  "");
        birdNames.put("Campephilus guatemalensis",  "");
        birdNames.put("Toxostoma rufum",  "");
        birdNames.put("Leptotila verreauxi",  "");
        birdNames.put("Nyctibius jamaicensis",  "");
        birdNames.put("Anas penelope",  "");
        birdNames.put("Buteo plagiatus",  "");
        birdNames.put("Selasphorus calliope",  "");
        birdNames.put("Megascops kennicottii",  "");
        birdNames.put("Porphyrio poliocephalus",  "");
        birdNames.put("Megascops asio",  "");
        birdNames.put("Zenaida auriculata",  "");
        birdNames.put("Hymenolaimus malacorhynchos",  "Blue duck");
        birdNames.put("Setophaga caerulescens",  "");
        birdNames.put("Camptostoma imberbe",  "");
        birdNames.put("Caracara plancus",  "");
        birdNames.put("Columbina passerina",  "");
        birdNames.put("Eupsittula nana",  "");
        birdNames.put("Nestor notabilis",  "Kea");
        birdNames.put("Columbina talpacoti",  "");
        birdNames.put("Geopelia striata",  "");
        birdNames.put("Athene noctua",  "Little Owl");
        birdNames.put("Crotophaga ani",  "");
        birdNames.put("Sialia sialis",  "");
        birdNames.put("Platalea alba",  "");
        birdNames.put("Bubo virginianus",  "");
        birdNames.put("Petrochelidon fulva",  "");
        birdNames.put("Progne subis",  "");
        birdNames.put("Setophaga coronata auduboni",  "");
        birdNames.put("Hirundo neoxena",  "Welcome swallow");
        birdNames.put("Hirundo rustica",  "");
        birdNames.put("Calidris virgata",  "");
        birdNames.put("Calidris pugnax",  "");
        birdNames.put("Platalea regia",  "Royal Spoonbill");
                birdNames.put("Tachycineta thalassina",  "");
        birdNames.put("Bostrychia hagedash",  "");
        birdNames.put("Riparia riparia",  "");
        birdNames.put("Eudocimus albus",  "");
        birdNames.put("Plegadis falcinellus",  "Glossy Ibis");
        birdNames.put("Plegadis chihi",  "");
        birdNames.put("Corvus corax",  "");
        birdNames.put("Stelgidopteryx serripennis",  "");
        birdNames.put("Sula dactylatra",  "Masked booby");
        birdNames.put("Sula sula",  "Red-footed booby");
        birdNames.put("Sula leucogaster",  "Brown booby");
        birdNames.put("Morus serrator",  "Gannet");
        birdNames.put("Eudyptula minor",  "Little Blue Penguin");
        birdNames.put("Megadyptes antipodes",  "Penguin");
        birdNames.put("Scopus umbretta",  "");
        birdNames.put("Troglodytes troglodytes",  "");
        birdNames.put("Calidris canutus",  "Lesser Knot");
        birdNames.put("Lanius collurio",  "");
        birdNames.put("Calidris bairdii",  "");
        birdNames.put("Meleagris gallopavo intermedia",  "Wild Turkey");
        birdNames.put("Calidris mauri",  "Sandpiper");
        birdNames.put("Calidris maritima",  "");
        birdNames.put("Calidris alpina",  "");
        birdNames.put("Calidris ferruginea",  "Sandpiper");
        birdNames.put("Calidris melanotos",  "Sandpiper");
        birdNames.put("Limnodromus griseus",  "");
        birdNames.put("Malurus cyaneus",  "");
        birdNames.put("Tringa nebularia",  "Greenshank");
        birdNames.put("Todiramphus sanctus vagans",  "Kingfisher");
        birdNames.put("Tringa ochropus",  "");
        birdNames.put("Tringa glareola",  "");
        birdNames.put("Tringa melanoleuca",  "");
        birdNames.put("Tringa flavipes",  "");
        birdNames.put("Numenius arquata",  "Curlew");
        birdNames.put("Numenius phaeopus",  "Curlew");
        birdNames.put("Phalacrocorax carbo novaehollandiae",  "Black shag");
        birdNames.put("Petroica macrocephala macrocephala",  "Tomtit");
        birdNames.put("Petroica australis longipes",  "Robin");
        birdNames.put("Prosthemadera novaeseelandiae novaeseelandiae",  "Tūī");
        birdNames.put("Asio flammeus",  "");
        birdNames.put("Rhipidura fuliginosa fuliginosa",  "Fantail");
        birdNames.put("Scolopax minor",  "");
        birdNames.put("Arenaria interpres",  "Ruddy Turnstone");
        birdNames.put("Arenaria melanocephala",  "");
        birdNames.put("Rhipidura fuliginosa placabilis",  "Fantail");
        birdNames.put("Limosa limosa",  "Godwit");
        birdNames.put("Limosa haemastica",  "Godwit");
        birdNames.put("Limosa fedoa",  "Godwit");
        birdNames.put("Phalaropus lobatus",  "");
        birdNames.put("Bartramia longicauda",  "");
        birdNames.put("Limosa lapponica",  "Godwit");
        birdNames.put("Aegolius acadicus",  "");
        birdNames.put("Actitis hypoleucos",  "Sandpiper");
        birdNames.put("Trichoglossus haematodus",  "Lorikeet");
        birdNames.put("Surnia ulula",  "");
        birdNames.put("Polioptila caerulea",  "");
        birdNames.put("Spizella passerina",  "");
        birdNames.put("Pycnonotus jocosus",  "");
        birdNames.put("Passerina cyanea",  "");
        birdNames.put("Passerina versicolor",  "");
        birdNames.put("Manorina melanocephala",  "");
        birdNames.put("Ocyphaps lophotes",  "Crested Pigeon");
        birdNames.put("Jabiru mycteria",  "");
        birdNames.put("Pycnonotus cafer",  "");
        birdNames.put("Anser cygnoides domesticus",  "Swan Goose");
        birdNames.put("Picus viridis",  "");
        birdNames.put("Phoebastria nigripes",  "");
        birdNames.put("Struthio camelus",  "");
        birdNames.put("Phoebastria immutabilis",  "");
        birdNames.put("Fulmarus glacialis",  "Fulmar");
        birdNames.put("Francolinus pondicerianus",  "");
        birdNames.put("Cynanthus latirostris",  "");
        birdNames.put("Podiceps nigricollis",  "");
        birdNames.put("Podiceps cristatus",  "Australasian Crested Grebe");
        birdNames.put("Podiceps auritus",  "");
        birdNames.put("Dendrocopos major",  "");
        birdNames.put("Podiceps grisegena",  "");
        birdNames.put("Tachybaptus ruficollis",  "Grebe");
        birdNames.put("Charadrius montanus",  "");
        birdNames.put("Phalacrocorax auritus",  "");
        birdNames.put("Phalacrocorax carbo",  "Black shag");
        birdNames.put("Phalacrocorax penicillatus",  "");
        birdNames.put("Aechmophorus clarkii",  "");
        birdNames.put("Pelecanus onocrotalus",  "");
        birdNames.put("Pelecanus erythrorhynchos",  "");
        birdNames.put("Zenaida macroura",  "");
        birdNames.put("Vanellus miles",  "Spur-winged Plover");
        birdNames.put("Larus occidentalis",  "");
        birdNames.put("Trogon massena",  "");
        birdNames.put("Larus thayeri",  "");
        birdNames.put("Larus heermanni",  "");
        birdNames.put("Larus livens",  "");
        birdNames.put("Larus canus",  "");
        birdNames.put("Larus glaucoides",  "");
        birdNames.put("Larus delawarensis",  "");
        birdNames.put("Trogon collaris",  "");
        birdNames.put("Zenaida asiatica",  "");
        birdNames.put("Larus fuscus",  "");
        birdNames.put("Larus californicus",  "");
        birdNames.put("Prosthemadera novaeseelandiae",  "Tūī");
        birdNames.put("Trogon elegans",  "");
        birdNames.put("Larus glaucescens",  "");
        birdNames.put("Trogon citreolus",  "");
        birdNames.put("Cepphus columba",  "");
        birdNames.put("Himantopus leucocephalus",  "Stilt");
        birdNames.put("Cepphus grylle",  "");
        birdNames.put("Anthornis melanura",  "Bellbird");
        birdNames.put("Leptoptilos crumenifer",  "");
        birdNames.put("Threskiornis moluccus",  "");
        birdNames.put("Thraupis episcopus",  "");
        birdNames.put("Geranoaetus albicaudatus",  "");
        birdNames.put("Sterna paradisaea",  "Arctic Tern");
        birdNames.put("Sterna hirundo",  "Tern");
        birdNames.put("Sterna forsteri",  "");
        birdNames.put("Lanius excubitor",  "");
        birdNames.put("Pharomachrus mocinno",  "");
        birdNames.put("Sterna striata",  "White Fronted Tern");
        birdNames.put("Stercorarius parasiticus",  "Skua");
        birdNames.put("Stercorarius pomarinus",  "Skua");
        birdNames.put("Anas gracilis",  "Grey teal");
        birdNames.put("Rissa tridactyla",  "");
        birdNames.put("Rynchops niger",  "");
        birdNames.put("Alca torda",  "");
        birdNames.put("Fratercula arctica",  "");
        birdNames.put("Fratercula cirrhata",  "");
        birdNames.put("Turdus merula",  "Blackbird");
        birdNames.put("Turdus plumbeus",  "");
        birdNames.put("Turdus grayi",  "");
        birdNames.put("Turdus migratorius",  "");
        birdNames.put("Turdus viscivorus",  "");
        birdNames.put("Cerorhinca monocerata",  "");
        birdNames.put("Turdus philomelos",  "Song thrush");
        birdNames.put("Galbula ruficauda",  "");
        birdNames.put("Jacana spinosa",  "");
        birdNames.put("Saxicola rubicola",  "");
        birdNames.put("Upupa epops",  "");
        birdNames.put("Euphagus carolinus",  "");
        birdNames.put("Gavia pacifica",  "");
        birdNames.put("Mimus gilvus",  "");
        birdNames.put("Passer italiae",  "");
        birdNames.put("Gavia immer",  "");
        birdNames.put("Gavia stellata",  "");
        birdNames.put("Oenanthe oenanthe",  "");
        birdNames.put("Fregata magnificens",  "Frigatebird");
                birdNames.put("Fregata minor",  "Frigatebird");
        birdNames.put("Falco subbuteo",  "");
        birdNames.put("Falco mexicanus",  "");
        birdNames.put("Falco femoralis",  "");
        birdNames.put("Falco peregrinus",  "");
        birdNames.put("Falco rufigularis",  "");
        birdNames.put("Falco sparverius",  "");
        birdNames.put("Strix varia",  "");
        birdNames.put("Falco columbarius",  "");
        birdNames.put("Gallinula chloropus",  "Moorhen");
        birdNames.put("Cardellina pusilla",  "");
        birdNames.put("Catharus ustulatus",  "");
        birdNames.put("Falco novaeseelandiae",  "New Zealand falcon");
        birdNames.put("Catharus guttatus",  "");
        birdNames.put("Catharus fuscescens",  "");
        birdNames.put("Caracara cheriway",  "");
        birdNames.put("Herpetotheres cachinnans",  "");
        birdNames.put("Calcarius lapponicus",  "");
        birdNames.put("Milvago chimachima",  "");
        birdNames.put("Ciconia ciconia",  "");
        birdNames.put("Mycteria americana",  "");
        birdNames.put("Mycteria ibis",  "");
        birdNames.put("Sialia mexicana",  "");
        birdNames.put("Ephippiorhynchus senegalensis",  "");
        birdNames.put("Cathartes aura",  "");
        birdNames.put("Myadestes townsendi",  "");
        birdNames.put("Cathartes burrovianus",  "");
        birdNames.put("Sarcoramphus papa",  "");
        birdNames.put("Coragyps atratus",  "");
        birdNames.put("Strix nebulosa",  "");
        birdNames.put("Anastomus lamelligerus",  "");
        birdNames.put("Pluvialis squatarola",  "Grey Plover");
        birdNames.put("Gymnogyps californianus",  "");
        birdNames.put("Muscicapa striata",  "");
        birdNames.put("Charadrius vociferus",  "");
        birdNames.put("Charadrius wilsonia",  "");
        birdNames.put("Charadrius melodus",  "");
        birdNames.put("Phoenicurus phoenicurus",  "");
        birdNames.put("Phoenicurus ochruros",  "");
        birdNames.put("Charadrius dubius",  "");
        birdNames.put("Eumomota superciliosa",  "");
        birdNames.put("Anas querquedula",  "");
        birdNames.put("Himantopus mexicanus",  "");
        birdNames.put("Haematopus bachmani",  "Black Oystercatcher");
        birdNames.put("Pica pica",  "");
        birdNames.put("Haematopus ostralegus",  "Oystercatcher");
        birdNames.put("Haematopus unicolor",  "Variable Oystercatcher");
        birdNames.put("Vanellus vanellus",  "");
        birdNames.put("Vanellus spinosus",  "");
        birdNames.put("Vanellus armatus",  "");
        birdNames.put("Luscinia svecica",  "");
        birdNames.put("Columbina inca",  "");
        birdNames.put("Recurvirostra avosetta",  "");
        birdNames.put("Phasianus colchicus",  "Ring-necked Pheasant");
        birdNames.put("Pluvialis dominica",  "Golden Plover");
        birdNames.put("Cinclus mexicanus",  "");
        birdNames.put("Erithacus rubecula",  "");
        birdNames.put("Melanerpes aurifrons",  "");
        birdNames.put("Charadrius hiaticula",  "");
        birdNames.put("Egretta gularis",  "");
        birdNames.put("Egretta caerulea",  "");
        birdNames.put("Egretta tricolor",  "");
        birdNames.put("Egretta thula",  "");
        birdNames.put("Egretta garzetta",  "Little Egret");
        birdNames.put("Egretta sacra",  "Reef heron");
        birdNames.put("Monticola solitarius",  "");
        birdNames.put("Ardea cocoi",  "");
        birdNames.put("Ardea cinerea",  "Grey Heron");
        birdNames.put("Ardea herodias",  "");
        birdNames.put("Nycticorax nycticorax",  "Night-Heron");
        birdNames.put("Turdus rufopalliatus",  "");
        birdNames.put("Ardeola ralloides",  "");
        birdNames.put("Nyctanassa violacea",  "");
        birdNames.put("Aramides cajaneus",  "");
        birdNames.put("Bubulcus ibis",  "Cattle Egret");
        birdNames.put("Butorides virescens",  "");
        birdNames.put("Porphyrio martinicus",  "");
        birdNames.put("Botaurus lentiginosus",  "");
        birdNames.put("Cochlearius cochlearius",  "");
        birdNames.put("Anhinga novaehollandiae",  "Darter");
        birdNames.put("Anhinga rufa",  "");
        birdNames.put("Melozone fusca",  "");
        birdNames.put("Aquila chrysaetos",  "");
        birdNames.put("Hylocichla mustelina",  "");
        birdNames.put("Aphelocoma wollweberi",  "");
        birdNames.put("Accipiter striatus",  "");
        birdNames.put("Accipiter nisus",  "");
        birdNames.put("Accipiter gentilis",  "");
        birdNames.put("Egretta rufescens",  "");
        birdNames.put("Bucephala clangula",  "");
        birdNames.put("Anous stolidus",  "Noddy");
        birdNames.put("Actitis macularius",  "Sandpiper");
        birdNames.put("Ardea purpurea",  "");
        birdNames.put("Todiramphus chloris",  "");
        birdNames.put("Grus americana",  "");
        birdNames.put("Himantopus himantopus",  "Stilt");
        birdNames.put("Glaucidium gnoma",  "");
        birdNames.put("Circus approximans",  "Harrier");
        birdNames.put("Circus aeruginosus",  "Harrier");
        birdNames.put("Phalacrocorax sulcirostris",  "Little Black Shag");
        birdNames.put("Buteo albonotatus",  "");
        birdNames.put("Butorides striata",  "");
        birdNames.put("Platalea ajaja",  "");
        birdNames.put("Buteo brachyurus",  "");
        birdNames.put("Ardea alba",  "White Heron");
        birdNames.put("Buteo swainsoni",  "");
        birdNames.put("Alectoris rufa",  "Partridge");
        birdNames.put("Buteo lineatus",  "");
        birdNames.put("Buteo jamaicensis",  "");
        birdNames.put("Charadrius nivosus",  "");
        birdNames.put("Tringa incana",  "Tattler");
        birdNames.put("Tringa semipalmata",  "");
        birdNames.put("Terathopius ecaudatus",  "");
        birdNames.put("Gallinago delicata",  "");
        birdNames.put("Buteogallus anthracinus",  "");
        birdNames.put("Chroicocephalus philadelphia",  "");
        birdNames.put("Circaetus gallicus",  "");
        birdNames.put("Chroicocephalus novaehollandiae",  "Red-billed Gull");
        birdNames.put("Chroicocephalus ridibundus",  "");
        birdNames.put("Leucophaeus atricilla",  "Laughing Gull");
        birdNames.put("Leucophaeus pipixcan",  "Franklin's Gull");
        birdNames.put("Onychoprion fuscatus",  "Sooty Tern");
        birdNames.put("Sternula antillarum",  "");
        birdNames.put("Hydroprogne caspia",  "Caspian Tern");
        birdNames.put("Thalasseus maximus",  "");
        birdNames.put("Thalasseus bergii",  "");
        birdNames.put("Elanus leucurus",  "");
        birdNames.put("Alopochen aegyptiaca",  "");
        birdNames.put("Streptopelia senegalensis",  "");
        birdNames.put("Gerygone igata",  "Grey warbler");
        birdNames.put("Haliaeetus leucocephalus",  "");
        birdNames.put("Cistothorus platensis",  "");
        birdNames.put("Haliaeetus vocifer",  "");
        birdNames.put("Bubo scandiacus",  "");
        birdNames.put("Ciccaba virgata",  "");
        birdNames.put("Bonasa umbellus",  "");
        birdNames.put("Busarellus nigricollis",  "");
        birdNames.put("Rostrhamus sociabilis",  "");
        birdNames.put("Milvus milvus",  "");
        birdNames.put("Gyps fulvus",  "");
        birdNames.put("Ficedula hypoleuca",  "");
        birdNames.put("Momotus coeruliceps",  "");
        birdNames.put("Charadrius semipalmatus",  "");
        birdNames.put("Haliastur indus",  "");
        birdNames.put("Gyps africanus",  "");
        birdNames.put("Ictinia mississippiensis",  "");
        birdNames.put("Dives dives",  "");
        birdNames.put("Baeolophus atricristatus",  "");
        birdNames.put("Baeolophus bicolor",  "");
        birdNames.put("Baeolophus inornatus",  "");
        birdNames.put("Melospiza melodia",  "");
        birdNames.put("Spinus spinus",  "");
        birdNames.put("Motacilla alba",  "");
        birdNames.put("Certhia americana",  "");
        birdNames.put("Bucorvus leadbeateri",  "");
        birdNames.put("Anthus pratensis",  "");
        birdNames.put("Anthus rubescens",  "");
        birdNames.put("Tachycineta albilinea",  "");
        birdNames.put("Poecile carolinensis",  "");
        birdNames.put("Poecile atricapillus",  "");
        birdNames.put("Poecile gambeli",  "");
        birdNames.put("Poecile rufescens",  "");
        birdNames.put("Periparus ater",  "");
        birdNames.put("Chlorophanes spiza",  "");
        birdNames.put("Estrilda astrild",  "");
        birdNames.put("Cyanistes caeruleus",  "");
        birdNames.put("Sphyrapicus varius",  "");
        birdNames.put("Petrochelidon pyrrhonota",  "");
        birdNames.put("Troglodytes pacificus",  "");
        birdNames.put("Troglodytes hiemalis",  "");
        birdNames.put("Passer montanus",  "");
        birdNames.put("Passer domesticus",  " House sparrow");
        birdNames.put("Aphelocoma californica",  "");
        birdNames.put("Amazilia yucatanensis",  "");
        birdNames.put("Amazilia tzacatl",  "");
        birdNames.put("Dicrurus adsimilis",  "");
        birdNames.put("Amazilia violiceps",  "");
        birdNames.put("Lonchura punctulata",  "");
        birdNames.put("Tigrisoma mexicanum",  "");
        birdNames.put("Porphyrio melanotus melanotus",  "Pūkeko");
        birdNames.put("Melanitta americana",  "");
        birdNames.put("Spizella pallida",  "");
        birdNames.put("Amazilia rutila",  "");
        birdNames.put("Zenaida aurita",  "");
        birdNames.put("Prunella modularis",  "Dunnock");
        birdNames.put("Falco tinnunculus",  "");
        birdNames.put("Ixoreus naevius",  "");
        birdNames.put("Archilochus colubris",  "");
        birdNames.put("Lampornis clemenciae",  "");
        birdNames.put("Myiarchus tuberculifer",  "");
        birdNames.put("Setophaga ruticilla",  "");
        birdNames.put("Myiarchus tyrannulus",  "");
        birdNames.put("Zosterops lateralis",  "Silvereye");
        birdNames.put("Zonotrichia leucophrys",  "");
        birdNames.put("Agelaius phoeniceus",  "");
        birdNames.put("Parus major",  "");
        birdNames.put("Zonotrichia capensis",  "");
        birdNames.put("Oreothlypis peregrina",  "");
        birdNames.put("Oreothlypis celata",  "");
        birdNames.put("Oreothlypis ruficapilla",  "");
        birdNames.put("Geothlypis philadelphia",  "");
        birdNames.put("Geothlypis formosa",  "");
        birdNames.put("Setophaga tigrina",  "");
        birdNames.put("Setophaga americana",  "");
        birdNames.put("Setophaga magnolia",  "");
        birdNames.put("Setophaga castanea",  "");
        birdNames.put("Setophaga fusca",  "");
        birdNames.put("Setophaga petechia",  "");
        birdNames.put("Setophaga striata",  "");
        birdNames.put("Setophaga palmarum",  "");
        birdNames.put("Setophaga pinus",  "");
        birdNames.put("Setophaga coronata",  "");
        birdNames.put("Setophaga dominica",  "");
        birdNames.put("Campylopterus hemileucurus",  "");
        birdNames.put("Vireo cassinii",  "");
        birdNames.put("Setophaga nigrescens",  "");
        birdNames.put("Setophaga townsendi",  "");
        birdNames.put("Setophaga occidentalis",  "");
        birdNames.put("Setophaga chrysoparia",  "");
        birdNames.put("Setophaga virens",  "");
        birdNames.put("Cardellina canadensis",  "");
        birdNames.put("Cardellina rubra",  "");
        birdNames.put("Aphelocoma coerulescens",  "");
        birdNames.put("Melanerpes erythrocephalus",  "");
        birdNames.put("Emberiza calandra",  "");
        birdNames.put("Acanthis flammea",  "Redpoll");
        birdNames.put("Spinus pinus",  "");
        birdNames.put("Thraupis abbas",  "");
        birdNames.put("Spinus psaltria",  "");
        birdNames.put("Spinus lawrencei",  "");
        birdNames.put("Spinus tristis",  "");
        birdNames.put("Threskiornis aethiopicus",  "");
        birdNames.put("Gygis alba",  "White Tern");
        birdNames.put("Tachycineta bicolor",  "");
        birdNames.put("Larus dominicanus dominicanus",  "Black-backed Gull");
        birdNames.put("Lonchura oryzivora",  "");
        birdNames.put("Haematopus palliatus",  "Oystercatcher");
        birdNames.put("Chloris chloris",  "Greenfinch");
        birdNames.put("Accipiter cooperii",  "");
        birdNames.put("Vireo solitarius",  "");
        birdNames.put("Selasphorus platycercus",  "");
        birdNames.put("Chroicocephalus scopulins",  "Red-billed Gull");
        birdNames.put("Aechmophorus occidentalis",  "");
        birdNames.put("Hemiphaga novaeseelandiae",  "Kereru");
        birdNames.put("Xema sabini",  "");
        birdNames.put("Ramphastos sulfuratus",  "");
        birdNames.put("Dacelo novaeguineae",  "Laughing Kookaburra");
        birdNames.put("Fulica atra",  "Coot");
        birdNames.put("Hirundo rustica erythrogaster",  "");
        birdNames.put("Calypte costae",  "");
        birdNames.put("Calypte anna",  "");
        birdNames.put("Colaptes auratus cafer",  "");
        birdNames.put("Sula nebouxii",  "");
        birdNames.put("Copsychus saularis",  "");
        birdNames.put("Selasphorus sasin",  "");
        birdNames.put("Selasphorus rufus",  "");
        birdNames.put("Calothorax lucifer",  "");
        birdNames.put("Pycnonotus barbatus",  "");
        birdNames.put("Larus glaucescens × occidentalis",  "");
        birdNames.put("Aphelocoma woodhouseii",  "");
        birdNames.put("Florisuga mellivora",  "");
        birdNames.put("Haematopus finschi",  "Oystercatcher");
        birdNames.put("Falcipennis canadensis",  "");
        birdNames.put("Archilochus alexandri",  "");
        birdNames.put("Circus cyaneus",  "");
        birdNames.put("Ardea alba modesta",  "");
        birdNames.put("Myiarchus crinitus",  "");
        birdNames.put("Buteo regalis",  "");
        birdNames.put("Aeronautes saxatalis",  "");
        birdNames.put("Chaetura vauxi",  "");
        birdNames.put("Chaetura pelagica",  "");
        birdNames.put("Setophaga pensylvanica",  "");
        birdNames.put("Lanius ludovicianus",  "");
        birdNames.put("Anhinga anhinga",  "");
        birdNames.put("Acridotheres tristis",  "Myna");
        birdNames.put("Sitta pygmaea",  "");
        birdNames.put("Actophilornis africanus",  "");
        birdNames.put("Sitta canadensis",  "");
        birdNames.put("Sitta europaea",  "");
        birdNames.put("Sitta pusilla",  "");
        birdNames.put("Apus apus",  "");
        birdNames.put("Sturnus vulgaris",  "Starling");
        birdNames.put("Seiurus aurocapilla",  "");
        birdNames.put("Motacilla flava",  "");
        birdNames.put("Vireo griseus",  "");
        birdNames.put("Toxostoma longirostre",  "");
        birdNames.put("Calidris alba",  "Sanderling");
        birdNames.put("Toxostoma redivivum",  "");
        birdNames.put("Gallinula galeata",  "Moorhen");
        birdNames.put("Calidris himantopus",  "");
        birdNames.put("Eugenes fulgens",  "");
        birdNames.put("Icterus wagleri",  "");
        birdNames.put("Icterus parisorum",  "");
        birdNames.put("Buteo platypterus",  "");
        birdNames.put("Gallinago gallinago",  "");
        birdNames.put("Icterus spurius",  "");
        birdNames.put("Calidris minutilla",  "");
        birdNames.put("Dumetella carolinensis",  "");
        birdNames.put("Porphyrio hochstetteri",  "Takahē");
        birdNames.put("Calidris fuscicollis",  "");
        birdNames.put("Phalaropus tricolor",  " Phalarope");
        birdNames.put("Colaptes auratus auratus",  "");
        birdNames.put("Melanotis caerulescens",  "");
        birdNames.put("Tiaris olivaceus",  "");
        birdNames.put("Oreoscoptes montanus",  "");
        birdNames.put("Limnodromus scolopaceus",  "");
        birdNames.put("Tringa solitaria",  "");
        birdNames.put("Sitta carolinensis",  "");
        birdNames.put("Tringa totanus",  "");
        birdNames.put("Dendrocygna autumnalis",  "");
        birdNames.put("Dendrocygna viduata",  "");
        birdNames.put("Dendrocygna bicolor",  "");
        birdNames.put("Icterus abeillei",  "");
        birdNames.put("Vanellus chilensis",  "");
        birdNames.put("Cygnus buccinator",  "");
        birdNames.put("Cygnus cygnus",  "");
        birdNames.put("Cygnus columbianus",  "");
        birdNames.put("Cygnus olor",  "Mute swan");
        birdNames.put("Icterus galbula",  "");
        birdNames.put("Anas platyrhynchos",  "Mallard");
        birdNames.put("Anas acuta",  "Northern Pintail");
        birdNames.put("Anas crecca",  "");
        birdNames.put("Anas cyanoptera",  "");
        birdNames.put("Anas fulvigula",  "");
        birdNames.put("Anas discors",  "");
        birdNames.put("Anas strepera",  "");
        birdNames.put("Anas clypeata",  "Northern Shoveler");
        birdNames.put("Anas chlorotis",  "Brown teal");
        birdNames.put("Rhipidura leucophrys",  "");
        birdNames.put("Anas americana",  "");
        birdNames.put("Bucephala albeola",  "");
        birdNames.put("Mergus serrator",  "");
        birdNames.put("Mergus merganser",  "");
        birdNames.put("Anser anser",  "Greylag goose");
        birdNames.put("Anser albifrons",  "");
        birdNames.put("Somateria mollissima",  "");
        birdNames.put("Rallus obsoletus",  "");
        birdNames.put("Platycercus elegans",  "Rosella");
        birdNames.put("Melanitta fusca",  "");
        birdNames.put("Milvus migrans",  "Black kite");
        birdNames.put("Gelochelidon nilotica",  "Gull-billed Tern");
        birdNames.put("Ninox novaeseelandiae novaeseelandiae",  "Ruru");
        birdNames.put("Melanitta perspicillata",  "");
        birdNames.put("Aythya collaris",  "");
        birdNames.put("Aythya ferina",  "");
        birdNames.put("Aythya fuligula",  "");
        birdNames.put("Numenius americanus",  "Curlew");
        birdNames.put("Chen caerulescens",  "");
        birdNames.put("Chamaea fasciata",  "");
        birdNames.put("Branta canadensis",  "Canada Goose");
        birdNames.put("Thalasseus elegans",  "");
        birdNames.put("Branta sandvicensis",  "");
        birdNames.put("Aythya americana",  "");
        birdNames.put("Aix sponsa",  "Wood Duck");
        birdNames.put("Lophodytes cucullatus",  "");
        birdNames.put("Histrionicus histrionicus",  "");
        birdNames.put("Aratinga nenday",  "");
        birdNames.put("Psittacara holochlorus",  "");
        birdNames.put("Cairina moschata",  "Muscovy Duck");
        birdNames.put("Netta rufina",  "");
        birdNames.put("Psittacara erythrogenys",  "");
        birdNames.put("Sayornis saya",  "");
        birdNames.put("Aythya valisineria",  "");
        birdNames.put("Picoides albolarvatus",  "");
        birdNames.put("Vermivora cyanoptera",  "");
        birdNames.put("Corvus caurinus",  "");
        birdNames.put("Asio otus",  "");
        birdNames.put("Corvus brachyrhynchos",  "");
        birdNames.put("Clangula hyemalis",  "");
        birdNames.put("Chenonetta jubata",  "Australian wood duck");
        birdNames.put("Thalasseus sandvicensis",  "");
        birdNames.put("Eolophus roseicapilla",  "Galah");
        birdNames.put("Colaptes rubiginosus",  "");
        birdNames.put("Meleagris gallopavo silvestris",  "Wild Turkey");
        birdNames.put("Ptiliogonys cinereus",  "");
        birdNames.put("Elanoides forficatus",  "");
        birdNames.put("Carduelis carduelis",  "European goldfinch");
        birdNames.put("Cassiculus melanicterus",  "");
        birdNames.put("Dendragapus fuliginosus",  "");
        birdNames.put("Psaltriparus minimus",  "");
        birdNames.put("Aegithalos caudatus",  "");
        birdNames.put("Zosterops lateralis lateralis",  "Silvereye");
        birdNames.put("Haliaeetus leucogaster",  "White-bellied sea eagle");
        birdNames.put("Uria aalge",  "");
        birdNames.put("Tringa semipalmata inornatus",  "");
        birdNames.put("Alauda arvensis",  "Eurasian skylark");
        birdNames.put("Galerida cristata",  "");
        birdNames.put("Delichon urbicum",  "");
        birdNames.put("Helmitheros vermivorum",  "");
        birdNames.put("Hylocharis leucotis",  "");
        birdNames.put("Mimus polyglottos",  "");
        birdNames.put("Gymnorhina tibicen",  "Magpie");
        birdNames.put("Alcedo atthis",  "");
        birdNames.put("Streptopelia chinensis",  "Spotted Dove");
        birdNames.put("Bombycilla cedrorum",  "");
        birdNames.put("Bombycilla garrulus",  "");
        birdNames.put("Tadorna tadorna",  "");
        birdNames.put("Petroica australis australis",  "Robin");
        birdNames.put("Amazona autumnalis",  "");
        birdNames.put("Dendragapus obscurus",  "");
        birdNames.put("Catherpes mexicanus",  "");
        birdNames.put("Tadorna ferruginea",  "");
        birdNames.put("Campylorhynchus brunneicapillus",  "");
        birdNames.put("Campylorhynchus rufinucha",  "");
        birdNames.put("Rhipidura fuliginosa",  "Fantail");
        birdNames.put("Polioptila melanura",  "");
        birdNames.put("Pelecanus occidentalis carolinensis",  "");
        birdNames.put("Melozone aberti",  "ss");
        birdNames.put("Melozone crissalis",  "");
        birdNames.put("Thryothorus ludovicianus",  "");
        birdNames.put("Parabuteo unicinctus",  "");
        birdNames.put("Anas platyrhynchos domesticus",  "Mallard");
        birdNames.put("Troglodytes aedon",  "");
        birdNames.put("Buteo lineatus elegans",  "");
        birdNames.put("Thamnophilus doliatus",  "");
        birdNames.put("Thryomanes bewickii",  "");
        birdNames.put("Tadorna variegata",  "Paradise shelduck");
        birdNames.put("Myioborus miniatus",  "");
        birdNames.put("Phalacrocorax varius varius",  "Pied shag");
        birdNames.put("Myioborus pictus",  "");
        birdNames.put("Larus argentatus smithsonianus",  "");
        birdNames.put("Parkesia motacilla",  "");
        birdNames.put("Sula granti",  "");
        birdNames.put("Ara macao",  "");
        birdNames.put("Peucaea ruficauda",  "");
        birdNames.put("Calidris subruficollis",  "Sandpiper");
        birdNames.put("Phoenicopterus roseus",  "");
        birdNames.put("Morus bassanus",  "Gannet");
        birdNames.put("Pelecanus occidentalis californicus",  "");
        birdNames.put("Glaucidium brasilianum",  "");
        birdNames.put("Oxyura jamaicensis",  "");
        birdNames.put("Myiarchus cinerascens",  "");
        birdNames.put("Chloroceryle americana",  "");
        birdNames.put("Sturnella neglecta",  "");
        birdNames.put("Ramphastos ambiguus",  "");
        birdNames.put("Paroaria coronata",  "");
        birdNames.put("Buteo buteo",  "");
        birdNames.put("Myiodynastes luteiventris",  "");
        birdNames.put("Contopus sordidulus",  "");
        birdNames.put("Corvus corone",  "");
        birdNames.put("Cyanoramphus novaezelandiae",  "Red-Crowned Parakeet");
        birdNames.put("Contopus virens",  "");
        birdNames.put("Contopus pertinax",  "");
        birdNames.put("Contopus cooperi",  "");
        birdNames.put("Larus argentatus",  "");
        birdNames.put("Halcyon smyrnensis",  "");
        birdNames.put("Onychognathus morio",  "");
        birdNames.put("Cyanocompsa parellina",  "");
        birdNames.put("Cistothorus palustris",  "");
        birdNames.put("Tyto alba",  "Barn Owl");
        birdNames.put("Trogon caligatus",  "");
        birdNames.put("Corvus monedula",  "");
        birdNames.put("Corvus ossifragus",  "");
        birdNames.put("Spheniscus demersus",  "");
        birdNames.put("Corvus frugilegus",  "Rook");
        birdNames.put("Corvus splendens",  "");
        birdNames.put("Branta bernicla",  "");
        birdNames.put("Larus hyperboreus",  "");
        birdNames.put("Columba livia domestica",  "Pigeon");
        birdNames.put("Garrulus glandarius",  "");
        birdNames.put("Anser anser domesticus",  "Greylag Goose");
        birdNames.put("Mitrephanes phaeocercus",  "");
        birdNames.put("Ardenna creatopus",  "Shearwater");
        birdNames.put("Ardenna gravis",  "Shearwater");



        String commonName = birdNames.get(scientificName);

        if (!Objects.equals(commonName, "") && commonName != null) {
            return commonName;
        } else {
            return scientificName;
        }
    }
}
